services:
  wiremock:
    image: wiremock/wiremock:3.9.2
    command:
      - --verbose
    volumes:
      - ./translucid/mocks/wiremock:/home/wiremock
    ports:
      - "8081:8080"
    networks:
      - translucid
